<?php

namespace Database\Seeders;

use App\Models\Branch;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TenantChartOfAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * This seeder creates chart of accounts from embedded data with
     * a hierarchical tree structure and proper parent-child relationships.
     *
     * - Main accounts (رئيسي): branch_id = null
     * - Branch accounts (فرعي): branch_id = first available branch
     * - Translations: Arabic (ar) is default
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('chart_of_accounts')->truncate();
        DB::table('chart_of_account_translations')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');

        // Get account types
        $assetTypeId = DB::table('chart_of_account_types')->where('id', 1)->value('id') ?? 1;
        $liabilityTypeId = DB::table('chart_of_account_types')->where('id', 2)->value('id') ?? 2;
        $equityTypeId = DB::table('chart_of_account_types')->where('id', 3)->value('id') ?? 3;
        $revenueTypeId = DB::table('chart_of_account_types')->where('id', 4)->value('id') ?? 4;
        $expenseTypeId = DB::table('chart_of_account_types')->where('id', 5)->value('id') ?? 5;

        // Get user ID for created_by
        $userId = DB::table('users')->value('id') ?? 1;

        // Get branch ID for branch accounts (فرعي)
        $branchId = Branch::getDefaultBranch()?->id ?? Branch::first()?->id ?? null;

        // Get chart of accounts data
        $accountsData = $this->getChartOfAccountsData();

        // Map account types based on code patterns
        $typeMap = [
            '1' => $assetTypeId,
            '2' => $liabilityTypeId,
            '3' => $equityTypeId,
            '4' => $revenueTypeId,
            '5' => $expenseTypeId,
        ];

        // Update type_id based on first digit of code
        foreach ($accountsData as &$account) {
            $firstDigit = substr($account['code'], 0, 1);
            $account['type_id'] = $typeMap[$firstDigit] ?? $assetTypeId;
        }
        unset($account);

        // Create accounts with proper parent relationships
        $codeToIdMap = [];
        $order = 1;

        foreach ($accountsData as $accountData) {
            $parentId = null;
            if ($accountData['parent_code']) {
                $parentId = $codeToIdMap[$accountData['parent_code']] ?? null;
            }

            // Set branch_id: null for main accounts, branch_id for branch accounts
            $accountBranchId = $accountData['is_main'] ? null : $branchId;

            $accountId = DB::table('chart_of_accounts')->insertGetId([
                'name' => $accountData['name_en'], // Use English name as default
                'code' => $accountData['code'],
                'type_id' => $accountData['type_id'],
                'parent_id' => $parentId,
                'order' => $order++,
                'is_active' => true,
                'created_by' => $userId,
                'branch_id' => $accountBranchId,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            $codeToIdMap[$accountData['code']] = $accountId;

            // Create translations - Arabic (ar) is default
            DB::table('chart_of_account_translations')->insert([
                [
                    'chart_of_account_id' => $accountId,
                    'locale' => 'ar',
                    'name' => $accountData['name_ar'],
                    'description' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'chart_of_account_id' => $accountId,
                    'locale' => 'en',
                    'name' => $accountData['name_en'],
                    'description' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }

        $this->command->info('Chart of Accounts seeded successfully!');
        $this->command->info('Created '.count($accountsData).' chart of accounts');
        $this->command->info('Main accounts (branch_id = null): '.count(array_filter($accountsData, fn ($a) => $a['is_main'])));
        $this->command->info('Branch accounts (branch_id set): '.count(array_filter($accountsData, fn ($a) => ! $a['is_main'])));
    }

    private function getChartOfAccountsData(): array
    {
        return [
            [
                'code' => '1',
                'name_ar' => 'الاصول',
                'name_en' => 'Assets',
                'type_id' => 1,
                'parent_code' => null,
                'level' => 1,
                'is_main' => true,
            ],
            [
                'code' => '2',
                'name_ar' => 'الخصوم',
                'name_en' => 'Liabilities and Equity',
                'type_id' => 2,
                'parent_code' => null,
                'level' => 1,
                'is_main' => true,
            ],
            [
                'code' => '3',
                'name_ar' => 'المصروفات',
                'name_en' => 'Expenses',
                'type_id' => 3,
                'parent_code' => null,
                'level' => 1,
                'is_main' => true,
            ],
            [
                'code' => '4',
                'name_ar' => 'الايرادات',
                'name_en' => 'Revenue',
                'type_id' => 4,
                'parent_code' => null,
                'level' => 1,
                'is_main' => true,
            ],
            [
                'code' => '11',
                'name_ar' => 'الاصول الغير متداولة',
                'name_en' => 'Non-Current Assets',
                'type_id' => 1,
                'parent_code' => '1',
                'level' => 2,
                'is_main' => true,
            ],
            [
                'code' => '12',
                'name_ar' => 'الاصول المتداولة',
                'name_en' => 'Current Assets',
                'type_id' => 1,
                'parent_code' => '1',
                'level' => 2,
                'is_main' => true,
            ],
            [
                'code' => '21',
                'name_ar' => 'حقوق الملكية وراس المال',
                'name_en' => 'Owner\'s Equity.',
                'type_id' => 2,
                'parent_code' => '2',
                'level' => 2,
                'is_main' => true,
            ],
            [
                'code' => '22',
                'name_ar' => 'الخصوم الغير متداولة',
                'name_en' => 'Non-Current Liabilities',
                'type_id' => 2,
                'parent_code' => '2',
                'level' => 2,
                'is_main' => true,
            ],
            [
                'code' => '23',
                'name_ar' => 'الخصوم المتداولة',
                'name_en' => 'Current Liabilities',
                'type_id' => 2,
                'parent_code' => '2',
                'level' => 2,
                'is_main' => true,
            ],
            [
                'code' => '31',
                'name_ar' => 'تكلفة النشاط',
                'name_en' => 'Cost of Activity',
                'type_id' => 3,
                'parent_code' => '3',
                'level' => 2,
                'is_main' => true,
            ],
            [
                'code' => '32',
                'name_ar' => 'مصاريف النشاط',
                'name_en' => 'Activity Expenses',
                'type_id' => 3,
                'parent_code' => '3',
                'level' => 2,
                'is_main' => true,
            ],
            [
                'code' => '41',
                'name_ar' => 'ايرادات النشاط',
                'name_en' => 'Activity Revenue',
                'type_id' => 4,
                'parent_code' => '4',
                'level' => 2,
                'is_main' => true,
            ],
            [
                'code' => '42',
                'name_ar' => 'الايرادات العرضية والاخرى',
                'name_en' => 'Incidental and other revenues',
                'type_id' => 4,
                'parent_code' => '4',
                'level' => 2,
                'is_main' => true,
            ],
            [
                'code' => '111',
                'name_ar' => 'صافي الأصول الثابتة',
                'name_en' => 'Net Fixed Assets',
                'type_id' => 1,
                'parent_code' => '11',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '112',
                'name_ar' => 'مشاريع قيد التنفيذ',
                'name_en' => 'Work In Progress',
                'type_id' => 1,
                'parent_code' => '11',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '113',
                'name_ar' => 'الأصول المعنوية',
                'name_en' => 'Intangible assets',
                'type_id' => 1,
                'parent_code' => '11',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '114',
                'name_ar' => 'نفقات ايرادية مؤجلة (التاسيس)',
                'name_en' => 'Deferred Expenditure(Organization Cost)',
                'type_id' => 1,
                'parent_code' => '11',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '115',
                'name_ar' => 'التوظيفات والاستثمارات طويلة الأجل',
                'name_en' => 'Long-Term Investments',
                'type_id' => 1,
                'parent_code' => '11',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '121',
                'name_ar' => 'المخزون',
                'name_en' => 'Inventories',
                'type_id' => 1,
                'parent_code' => '12',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '122',
                'name_ar' => 'الاعتمادات المستندية والتحويلات',
                'name_en' => 'Letters of Credit',
                'type_id' => 1,
                'parent_code' => '12',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '123',
                'name_ar' => 'المدينون',
                'name_en' => 'Debtors',
                'type_id' => 1,
                'parent_code' => '12',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '124',
                'name_ar' => 'الذمم المدينة',
                'name_en' => 'Other Accounts Receivable',
                'type_id' => 1,
                'parent_code' => '12',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '125',
                'name_ar' => 'اوارق القبض',
                'name_en' => 'Short Term Notes Receivables',
                'type_id' => 1,
                'parent_code' => '12',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '126',
                'name_ar' => 'النقدية وما في حكمها',
                'name_en' => 'Cash and Cash Equivalents',
                'type_id' => 1,
                'parent_code' => '12',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '127',
                'name_ar' => 'حساب العمليات الجارية',
                'name_en' => 'Current Account',
                'type_id' => 1,
                'parent_code' => '12',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '128',
                'name_ar' => 'الارصدة المدينة الاخرى',
                'name_en' => 'Other current assets',
                'type_id' => 1,
                'parent_code' => '12',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '211',
                'name_ar' => 'راس المال والاحتياطيات',
                'name_en' => 'Owner\'s Equity and Reserves',
                'type_id' => 2,
                'parent_code' => '21',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '221',
                'name_ar' => 'القروض والمرابحات طويلة الأجل',
                'name_en' => 'Long - Term Loan',
                'type_id' => 2,
                'parent_code' => '22',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '222',
                'name_ar' => 'المخصصات طويلة الأجل',
                'name_en' => 'Long - Term Provision',
                'type_id' => 2,
                'parent_code' => '22',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '233',
                'name_ar' => 'الدائنون',
                'name_en' => 'Accounts Payables',
                'type_id' => 2,
                'parent_code' => '23',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '234',
                'name_ar' => 'الذمم الدائنة',
                'name_en' => 'Other Accounts Payables',
                'type_id' => 2,
                'parent_code' => '23',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '235',
                'name_ar' => 'اوارق الدفع',
                'name_en' => 'Notes Payable',
                'type_id' => 2,
                'parent_code' => '23',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '236',
                'name_ar' => 'القروض قصيرة الاجل',
                'name_en' => 'Short - Term Loan',
                'type_id' => 2,
                'parent_code' => '23',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '238',
                'name_ar' => 'ارصدة دائنة اخرى',
                'name_en' => 'Other Credit Balances',
                'type_id' => 2,
                'parent_code' => '23',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '311',
                'name_ar' => 'تكلفة  المبيعات',
                'name_en' => 'Cost of sale',
                'type_id' => 3,
                'parent_code' => '31',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '312',
                'name_ar' => 'التكاليف الإنتاجية',
                'name_en' => 'Production costs',
                'type_id' => 3,
                'parent_code' => '31',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '321',
                'name_ar' => 'المصاريف الادارية والعمومية',
                'name_en' => 'GENERAL and ADMINISTRATIVE EXPENSES',
                'type_id' => 3,
                'parent_code' => '32',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '322',
                'name_ar' => 'المصاريف التسويقية',
                'name_en' => 'Marketing expenses',
                'type_id' => 3,
                'parent_code' => '32',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '411',
                'name_ar' => 'ايرادات  المبيعات',
                'name_en' => 'Remittances Revenue',
                'type_id' => 4,
                'parent_code' => '41',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '412',
                'name_ar' => 'ايرادات مرتبطة بالنشاط',
                'name_en' => 'Business-related revenues',
                'type_id' => 4,
                'parent_code' => '41',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '421',
                'name_ar' => 'الايرادات العرضية',
                'name_en' => 'Incidental revenue',
                'type_id' => 4,
                'parent_code' => '42',
                'level' => 3,
                'is_main' => true,
            ],
            [
                'code' => '11101',
                'name_ar' => 'الاراضي',
                'name_en' => 'Lands',
                'type_id' => 1,
                'parent_code' => '111',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11102',
                'name_ar' => 'المباني والهناجر',
                'name_en' => 'Buildings',
                'type_id' => 1,
                'parent_code' => '111',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11103',
                'name_ar' => 'الالات والمعدات',
                'name_en' => 'Equipments and Machineries',
                'type_id' => 1,
                'parent_code' => '111',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11104',
                'name_ar' => 'السيارات ووسائل النقل',
                'name_en' => 'Transportation Assets',
                'type_id' => 1,
                'parent_code' => '111',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11105',
                'name_ar' => 'الاثاث والتركيبات',
                'name_en' => 'Furnitures and Decor',
                'type_id' => 1,
                'parent_code' => '111',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11106',
                'name_ar' => 'الكمبيوترات والشبكات وملحقاتها',
                'name_en' => 'Computers, Servers, Printers, …Etc.',
                'type_id' => 1,
                'parent_code' => '111',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11107',
                'name_ar' => 'الاجهزة  الالكترونية والكهربائية وملحقاتها',
                'name_en' => 'Electric Equipment',
                'type_id' => 1,
                'parent_code' => '111',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11108',
                'name_ar' => 'البرامج والتطبيقات',
                'name_en' => 'Programs',
                'type_id' => 1,
                'parent_code' => '111',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11109',
                'name_ar' => 'مجمعات الاهلاك',
                'name_en' => 'Accumulated Depreciation',
                'type_id' => 1,
                'parent_code' => '111',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11201',
                'name_ar' => 'مشاريع قيد التنفيذ اراضي',
                'name_en' => 'Work in Progress lands',
                'type_id' => 1,
                'parent_code' => '112',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11202',
                'name_ar' => 'مشاريع قيد التنفيذ مباني',
                'name_en' => 'Work in Progress Buildings',
                'type_id' => 1,
                'parent_code' => '112',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11203',
                'name_ar' => 'مشاريع قيد التنفيذ الات ومعدات',
                'name_en' => 'Work In Progress Equipments and Machineries',
                'type_id' => 1,
                'parent_code' => '112',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11204',
                'name_ar' => 'مشاريع قيد التنفيذ سيارات ووسائل نقل',
                'name_en' => 'Work In Progress Transportation Assets',
                'type_id' => 1,
                'parent_code' => '112',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11205',
                'name_ar' => 'مشاريع قيد التنفيذ الأثاث والتركيبات',
                'name_en' => 'Work In Progress Furnitures and Decor',
                'type_id' => 1,
                'parent_code' => '112',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11206',
                'name_ar' => 'مشاريع قيد التنفيذ الكمبيوترات والشبكات',
                'name_en' => 'Work In Progress Computers, Servers, Printers, …Etc.',
                'type_id' => 1,
                'parent_code' => '112',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11207',
                'name_ar' => 'مشاريع قيد التنفيذ الأجهزة الالكترونية والكهربائية',
                'name_en' => 'Work In Progress Electric Equipment',
                'type_id' => 1,
                'parent_code' => '112',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11208',
                'name_ar' => 'مشاريع قيد التنفيذ البرامج والتطبيقات',
                'name_en' => 'Work In Progress Programs',
                'type_id' => 1,
                'parent_code' => '112',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11209',
                'name_ar' => 'وسيط إضافات الأصول',
                'name_en' => 'Interfase Asset Additions',
                'type_id' => 1,
                'parent_code' => '112',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11301',
                'name_ar' => 'حقوق (الامتياز ,الشهرة , العلامات التجاريه )',
                'name_en' => 'Rights (franchise, goodwill, trademarks)',
                'type_id' => 1,
                'parent_code' => '113',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11401',
                'name_ar' => 'مصاريف (التأسيس, الدراسات والابحاث )',
                'name_en' => 'Expenses (establishment, studies and research)',
                'type_id' => 1,
                'parent_code' => '114',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11501',
                'name_ar' => 'الاستثمار في شركات شقيقة',
                'name_en' => 'Investments in Sisters Companies',
                'type_id' => 1,
                'parent_code' => '115',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11502',
                'name_ar' => 'الودائع',
                'name_en' => ' Deposits',
                'type_id' => 1,
                'parent_code' => '115',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11503',
                'name_ar' => 'الاستثمارفي سندات',
                'name_en' => 'Deposits in Bank',
                'type_id' => 1,
                'parent_code' => '115',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '11504',
                'name_ar' => 'الاستثمارفي اسهم',
                'name_en' => 'Stock investment',
                'type_id' => 1,
                'parent_code' => '115',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12101',
                'name_ar' => 'المخزون السلعي',
                'name_en' => 'Inventory',
                'type_id' => 1,
                'parent_code' => '121',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12103',
                'name_ar' => 'مخزون الإنتاج تحت الشتغيل',
                'name_en' => 'Stocks in operation',
                'type_id' => 1,
                'parent_code' => '121',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12201',
                'name_ar' => 'الاعتمادات المستندية',
                'name_en' => 'Letters of Credit',
                'type_id' => 1,
                'parent_code' => '122',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12301',
                'name_ar' => 'العملاء',
                'name_en' => 'Customers',
                'type_id' => 1,
                'parent_code' => '123',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12302',
                'name_ar' => 'الوكلاء (مؤسسات مالية )',
                'name_en' => 'Customers',
                'type_id' => 1,
                'parent_code' => '123',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12401',
                'name_ar' => 'سلف الموظفين',
                'name_en' => 'Personal Loans To Employees',
                'type_id' => 1,
                'parent_code' => '124',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12402',
                'name_ar' => 'عهد الموظفين',
                'name_en' => 'Temporary loans',
                'type_id' => 1,
                'parent_code' => '124',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12403',
                'name_ar' => 'ذمم مدينة أخرى',
                'name_en' => 'Other Accounts Receivable',
                'type_id' => 1,
                'parent_code' => '124',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12501',
                'name_ar' => 'اوراق قبض تحت التحصيل',
                'name_en' => 'Short Term Notes Receivables',
                'type_id' => 1,
                'parent_code' => '125',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12502',
                'name_ar' => 'اوارق قبض برسم التحصيل',
                'name_en' => 'Receivable Cheques Interface  by Collection',
                'type_id' => 1,
                'parent_code' => '125',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12601',
                'name_ar' => 'النقدية في الصناديق',
                'name_en' => 'Cash in Hand',
                'type_id' => 1,
                'parent_code' => '126',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12602',
                'name_ar' => 'النقدية في البنوك',
                'name_en' => 'Cash in Bank',
                'type_id' => 1,
                'parent_code' => '126',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12603',
                'name_ar' => 'نقدية لدى شركات صرافة',
                'name_en' => 'Cash in Exchangers',
                'type_id' => 1,
                'parent_code' => '126',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12701',
                'name_ar' => 'العمليات الجاريه بين الفروع',
                'name_en' => 'Branch Current Acount',
                'type_id' => 1,
                'parent_code' => '127',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12801',
                'name_ar' => 'الضمانات والتامينات المدينة',
                'name_en' => 'Debit Insurance',
                'type_id' => 1,
                'parent_code' => '128',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12802',
                'name_ar' => 'مصاريف مدفوعة مقدماً',
                'name_en' => 'Prepaid Expenditures',
                'type_id' => 1,
                'parent_code' => '128',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '12803',
                'name_ar' => 'إيرادات مستحقة',
                'name_en' => 'Accrued Revenues',
                'type_id' => 1,
                'parent_code' => '128',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '21101',
                'name_ar' => 'راس المال',
                'name_en' => 'Owner\'s Equity.',
                'type_id' => 2,
                'parent_code' => '211',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '21102',
                'name_ar' => 'الاحتياطيات',
                'name_en' => 'Reserves',
                'type_id' => 2,
                'parent_code' => '211',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '21103',
                'name_ar' => 'الأرباح والخسائر',
                'name_en' => 'Profit and loss',
                'type_id' => 2,
                'parent_code' => '211',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '21104',
                'name_ar' => 'جاري الشركاء',
                'name_en' => 'Partners\' Current Account',
                'type_id' => 2,
                'parent_code' => '211',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '22101',
                'name_ar' => 'القروض طويلة الأجل',
                'name_en' => 'Long - Term Loan',
                'type_id' => 2,
                'parent_code' => '221',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '22102',
                'name_ar' => 'المرابحات طويلة الأجل',
                'name_en' => 'Long - Term  loan Islamic Bank',
                'type_id' => 2,
                'parent_code' => '221',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '22201',
                'name_ar' => 'مخصصات الديون المشكوك فيها',
                'name_en' => 'Provision for Bad Debts',
                'type_id' => 2,
                'parent_code' => '222',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '22202',
                'name_ar' => 'مخصصات هبوط الاسعار',
                'name_en' => 'Provision for Devaluation',
                'type_id' => 2,
                'parent_code' => '222',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '22203',
                'name_ar' => 'مخصص الزكاة',
                'name_en' => 'Provision Zakat',
                'type_id' => 2,
                'parent_code' => '222',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '22204',
                'name_ar' => 'مخصصات هبوط الاستثمارات والأوراق المالية',
                'name_en' => 'Provision for Devaluation of Money Market',
                'type_id' => 2,
                'parent_code' => '222',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '22205',
                'name_ar' => 'مخصص الضرائب',
                'name_en' => 'Tax custom',
                'type_id' => 2,
                'parent_code' => '222',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '22206',
                'name_ar' => 'مخصص حقوق العاملين',
                'name_en' => 'Provision for workers\' rights',
                'type_id' => 2,
                'parent_code' => '222',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '22207',
                'name_ar' => 'مخصص الالتزامات القضائية والقانونية',
                'name_en' => 'Provision for judicial and legal obligations',
                'type_id' => 2,
                'parent_code' => '222',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '22209',
                'name_ar' => 'مخصص أخرى ومختلفة',
                'name_en' => 'Other and different custom',
                'type_id' => 2,
                'parent_code' => '222',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '23301',
                'name_ar' => 'الموردون',
                'name_en' => 'Foreign Creditors',
                'type_id' => 2,
                'parent_code' => '233',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '23302',
                'name_ar' => 'وكلاء صرافة (دائنون)',
                'name_en' => 'Exchange agents (creditors)',
                'type_id' => 2,
                'parent_code' => '233',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '23303',
                'name_ar' => 'عملاء صرافة (دائنون)',
                'name_en' => 'Exchange clients (payables)',
                'type_id' => 2,
                'parent_code' => '233',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '23401',
                'name_ar' => 'الذمم الدائنة المؤسسات والافراد',
                'name_en' => 'Accounts payable institutions and individuals',
                'type_id' => 2,
                'parent_code' => '234',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '23402',
                'name_ar' => 'الذمم الدائنة جهات حكومية',
                'name_en' => 'Accounts payable are government agencies',
                'type_id' => 2,
                'parent_code' => '234',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '23501',
                'name_ar' => 'اوراق الدفع',
                'name_en' => 'Payables  Cheques Interface  by Collection',
                'type_id' => 2,
                'parent_code' => '235',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '23601',
                'name_ar' => 'القروض قصيرة الاجل',
                'name_en' => 'Short - Term Loan',
                'type_id' => 2,
                'parent_code' => '236',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '23801',
                'name_ar' => 'المصاريف  المستحقة',
                'name_en' => 'Accrued Expenses',
                'type_id' => 2,
                'parent_code' => '238',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '23802',
                'name_ar' => 'الايرادات المدفوعة مقدماً',
                'name_en' => 'Prepaid Revenue',
                'type_id' => 2,
                'parent_code' => '238',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '31101',
                'name_ar' => 'تكلفة مبيعات',
                'name_en' => 'Cost of sale',
                'type_id' => 3,
                'parent_code' => '311',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '31102',
                'name_ar' => 'مردود مبيعات',
                'name_en' => 'Sales return',
                'type_id' => 3,
                'parent_code' => '311',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '31103',
                'name_ar' => 'تكلفة مردود المبيعات',
                'name_en' => 'Cost of Sales Return',
                'type_id' => 3,
                'parent_code' => '311',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '31104',
                'name_ar' => 'مردود مبيعات سنوات',
                'name_en' => 'Years sales return',
                'type_id' => 3,
                'parent_code' => '311',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '31105',
                'name_ar' => 'تكلفة مردود  المبيعات سنوات',
                'name_en' => 'The cost of sales return is years',
                'type_id' => 3,
                'parent_code' => '311',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '31106',
                'name_ar' => 'تكلفة الكميات المجانية',
                'name_en' => 'The cost of free quantities',
                'type_id' => 3,
                'parent_code' => '311',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '31107',
                'name_ar' => 'الخصم المسموح به',
                'name_en' => 'Allowed discount',
                'type_id' => 3,
                'parent_code' => '311',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '31201',
                'name_ar' => 'مصاريف الإنتاج تحت التشغيل',
                'name_en' => 'Production costs In-progress production costs',
                'type_id' => 3,
                'parent_code' => '312',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32101',
                'name_ar' => 'المرتبات والاجور وما حكمها',
                'name_en' => 'SALARIES and  WAGES',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32102',
                'name_ar' => 'المزايا الأخرى للعاملين',
                'name_en' => 'Other benefits for employees',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32103',
                'name_ar' => 'الايجارات',
                'name_en' => 'Rents',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32104',
                'name_ar' => 'الاتصالات والانترنت',
                'name_en' => 'Telecommunications and  Internet',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32105',
                'name_ar' => 'الكهرباء والمياه والوقود',
                'name_en' => 'Electricity and Water and Fuel and Oil',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32106',
                'name_ar' => 'القرطاسية والمطبوعات',
                'name_en' => 'Stationeries',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32107',
                'name_ar' => 'بدل السفر والانتقال والمواصلات',
                'name_en' => 'Travel and Transportation allowance',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32108',
                'name_ar' => 'مصاريف السيارات',
                'name_en' => 'Vehicle Expenses',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32109',
                'name_ar' => 'مصاريف الصيانة للمباني والاجهزة والاثاث',
                'name_en' => 'Maintenance of buildings and furniture hardware expenses',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32110',
                'name_ar' => 'مصاريف رسوم خدمات للجهات والمؤسسات الحكومية',
                'name_en' => 'Services and government institutions fees Expenses',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32111',
                'name_ar' => 'الضرائب',
                'name_en' => ' Taxes',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32112',
                'name_ar' => 'الزكاة',
                'name_en' => 'Zakat',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32113',
                'name_ar' => 'مصاريف التامين',
                'name_en' => 'Insurance Expenses',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32114',
                'name_ar' => 'الاستشارات والخدمات',
                'name_en' => 'Consulting and services',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32115',
                'name_ar' => ' المساعدات والمنح والتبرعات',
                'name_en' => 'assistance and grants',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32116',
                'name_ar' => 'الديون المعدومة والعجوزات',
                'name_en' => 'Bad debt and deficits',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32117',
                'name_ar' => 'الاهلاك والاطفاءت',
                'name_en' => 'Depreciation',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32118',
                'name_ar' => 'مصاريف وعمولات وفوائد بنكية',
                'name_en' => 'Bank fees and commissions',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32119',
                'name_ar' => 'خدمات امن وحراسة',
                'name_en' => 'Safety and Security',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32120',
                'name_ar' => 'فروق اسعار',
                'name_en' => 'price differences',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32121',
                'name_ar' => 'عدد وادوات',
                'name_en' => 'tools',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32122',
                'name_ar' => 'مصروفات سنوات سابقه',
                'name_en' => 'Expenses of previous years',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32129',
                'name_ar' => 'مصاريف عمومية اخرى',
                'name_en' => 'Public Expenses',
                'type_id' => 3,
                'parent_code' => '321',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32201',
                'name_ar' => 'الإعلانات والمطبوعات والندوات',
                'name_en' => 'Advertisements, publications and seminars',
                'type_id' => 3,
                'parent_code' => '322',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32202',
                'name_ar' => 'الاشتراك في هيئات محلية ودولية',
                'name_en' => 'Participation in local and international bodies',
                'type_id' => 3,
                'parent_code' => '322',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '32203',
                'name_ar' => 'مصاريف تسويقيه اخرى',
                'name_en' => 'Other Marketing expenses',
                'type_id' => 3,
                'parent_code' => '322',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '41101',
                'name_ar' => 'إيرادات المبيعات السلعيه والخدميه',
                'name_en' => 'Outward Remittances Revenue',
                'type_id' => 4,
                'parent_code' => '411',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '41201',
                'name_ar' => 'إيرادات الكميات المجانية',
                'name_en' => 'Free quantities revenue',
                'type_id' => 4,
                'parent_code' => '412',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '41202',
                'name_ar' => 'إيرادات الخصم المكتسب',
                'name_en' => 'Earned discount income',
                'type_id' => 4,
                'parent_code' => '412',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '42101',
                'name_ar' => 'ايردات الاستثمارات',
                'name_en' => 'Income from investments',
                'type_id' => 4,
                'parent_code' => '421',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '42102',
                'name_ar' => 'ايرادات اوراق مالية',
                'name_en' => 'Revenue securities',
                'type_id' => 4,
                'parent_code' => '421',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '42103',
                'name_ar' => 'إيرادات فروق العملة',
                'name_en' => 'Currency differential revenue',
                'type_id' => 4,
                'parent_code' => '421',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '42104',
                'name_ar' => 'إيرادات بيع الاصول',
                'name_en' => 'Asset sale revenue',
                'type_id' => 4,
                'parent_code' => '421',
                'level' => 4,
                'is_main' => false,
            ],
            [
                'code' => '42105',
                'name_ar' => 'الايرادات المتنوعة',
                'name_en' => 'Other Revenues',
                'type_id' => 4,
                'parent_code' => '421',
                'level' => 4,
                'is_main' => false,
            ],
        ];
    }
}
